### ISSUE TITLE
Pickadate options dont work

### ISSUE THREAD

**Issue by dzena** [AddJam/ember-cli-pickadate#2]
Whatever option I try to use doesn't make any change.

{{pick-a-time date=date format='T!ime selected: h:i a' formatLabel='<b>h</b>:i <!i>a</!i>' placeholder="Pick a time"}}

In this example nothing affects the component, it always uses standard format.

Any suggestions?

**Comment by chrissloey** [comment]
Try passing in those using the options attribute, everything passed in via options is used when creating the pickadate instance.

So instead of what you have, you could do
`{{pick-a-time date=date placeholder="Pick a time" options=opts}}`

where opts could be
`{ format: 'T!ime selected: h:i a', formatLabel: 'h:i <!i>a</!i>' }`

Hopefully that works!

**Comment by dzena** [comment]
Worked like a charm!
Thanks

Cheers

**Comment by chrissloey** [comment]
Great! 😊
