### ISSUE TITLE
assigning value, formatting date

### ISSUE THREAD

**Issue by zurnet** [AddJam/ember-cli-pickadate#28]
I'm not sure I understand how I pull the value from the datepicker.  For example, in ember you can do this:
`{{input value=dob}}`
and then the output can be:
`{{dob}}`

For the datepicker, I have this:
`{{pick-a-date date=(readonly date)  on-selected=(action (mut date)) placeholder="Pick a date" options=(readonly extraPickadateOptions)}}`

and if I do this:  {{date}} it will display the date, but a long form version of it?

My question is, what if I wanted to change the value, so instead of date.. it's dob  and then how do I display the same value `{{dob}}` ?

As of now it does this:
5, June 2016 (in the input field) and then displayed it shows: Sun Jun 05 2016 16:52:36 GMT-0400 (EDT)

**Comment by chrissloey** [comment]
Hey, sorry it took a while to get back to you!

The longer version you see is because the `{{date}}` contains a `Date` object (whereas in your `input` example, it would just be a string), if you do `new Date()` in a node repl / devtools console you'll see the same output. Formatting is just a generic Javascript thing rather than something this component would do, there are some solutions [here](https://stackoverflow.com/questions/1056728/where-can-i-find-documentation-on-formatting-a-date-in-javascript). I often use something like [moment.js](http://momentjs.com/) for more complicated formatting - the [ember-moment](https://github.com/stefanpenner/ember-moment) addon is pretty good for that.

Hope that helped! 😄

**Comment by chrissloey** [comment]
Closing this now, hope you got it working - happy to reopen if something else was the problem.

**Comment by zurnet** [comment]
I guess I don't understand how to define the value and then load the value back into the input field?  For example, how would I translate this:  {{input value=dob}} to use pick-a-date?  so the 'value' is defined as 'dob' and not 'date?  I tried changing 'date' to 'dob' in my {{pick-a-date}} tag but then it does not load in the dob value?

**Comment by chrissloey** [comment]
I'd need to see the component/controller code where you initialize the `dob` value. Sounds like it's a string and you need to provide a Date.

**Comment by zurnet** [comment]
I guess to clarify... I'm setting the date like this (in the config):  

```
date: {
format: 'yyyy-mm-dd',
}
```

if I store the date in my db, It's stored as "1999-08-07"

My handlebar code is this:

`{{pick-a-date date=dob on-selected=(action (mut dob)) placeholder="Pick a date" options=(readonly extraPickadateOptions)}}`

If I do this:  `{{dob}}` the date displays, but it does not show in the field... what shows in the field (input) is the current date, not the date in the db.

I tried doing this:
`{{pick-a-date value=dob}}`

But that doesn't seem to work either.... I'm gathering by what you're saying i need to set the date as a date object and not as a string for it to show the correct date?

**Comment by zurnet** [comment]
Looking at this further, it appears that yes it does need the date object passed for it to work.  Forgive me for the confusion.

**Comment by chrissloey** [comment]
Awesome glad you got it sorted :smile:
